### ISSUE TITLE
PushKit - VOIP Certificate Push Support

### ISSUE THREAD

**Issue by FredericJacobs** [noodlewerk/NWPusher#12]
I tried to setup NWPusher with a VOIP push certificate but I believe they are incorrectly parsed and not recognized by NWPusher.

**Comment by Jalamanta** [comment]
I have same issue, is there any plans to support PushKit?

**Comment by leonardvandriel** [comment]
Hi, this issue should be resolved in version 0.7.0. Could you verify that?

**Comment by superdev89** [comment]
Is it working now?

I've tested NWPusher voip push in iOS and no errors, but push is not delivered.
With the Pusher MacOS app, voip push is delivered successfully with same p12 file.
Any thought?
