### ISSUE TITLE
Command line support

### ISSUE THREAD

**Issue by owenfi** [noodlewerk/NWPusher#13]
Has any work been done to make NWPusher support the command line?

What I'd like to do is support sending a push from a command line build script, something like:
    $> NWPusher --token <1234afaf - owen> --cert <sandbox cert> --body {"aps":"message..." ...}

And have a push notification be sent to the respective device.

It'd be helpful to plug that into build scripts, cron jobs, etc.

If that sounds useful to anyone else I'll try to work on a pull request with support.

**Comment by leonardvandriel** [comment]
Hi @owenfi. I don't know of any work on command-line support. I do see the value for use in scripts and the likes. Let me know if you plan to do a large pull request. Thanks!
