### ISSUE TITLE
Is it possible to remove imported certificates from pusher "caché"?

### ISSUE THREAD

**Issue by vCrespoP** [noodlewerk/NWPusher#16]
You have a selector to pick a push certificate. Is it possible to remove any of those (without affecting the keychain, of course)?

Where can we delete them by hand? Just in case, the previous is not going to happen :D

Thanks man!

**Comment by leonardvandriel** [comment]
Hi, the certificates listed are not cached, but instead taken directly from the keychain using `[NWSecTools keychainCertificatesWithError:error]`. Therefore the only way to remove items from the selector is by removing them from your keychain. See `[NWAppDelegate loadCertificatesFromKeychain]` for more details.

**Comment by leonardvandriel** [comment]
@vCrespoP I'm closing the issue, unless you feel this should be turned into a feature request..
