### ISSUE TITLE
Update Pod version to 0.7.0

### ISSUE THREAD

**Issue by vitorsdcs** [noodlewerk/NWPusher#20]
I cannot install the latest version via CocoaPods since it is not up-to-date: https://cocoapods.org/?q=nwpusher

**Comment by leonardvandriel** [comment]
Hi, thanks for reporting. I've updated the pod on cocoapods. To do this I had to fix a bug and bump the version to 0.7.1.

Does this resolve the issue?

**Comment by vitorsdcs** [comment]
Yes. Thanks!
