### ISSUE TITLE
Change icon?

### ISSUE THREAD

**Issue by jessamynsmith** [noodlewerk/NWPusher#21]
This is a great app, very helpful. The icon is kind of disturbing; would you consider changing it to something more neutral?

**Comment by vtellez** [comment]
+1

**Comment by leonardvandriel** [comment]
https://github.com/noodlewerk/NWPusher/issues/14

**Comment by frankvanboheemen** [comment]
How is this for a icon?

![uphillpushnotification](https://cloud.githubusercontent.com/assets/4217570/16002968/b0625786-315a-11e6-8dfb-e1cb2c6d2b3a.png)

**Comment by SpacyRicochet** [comment]
Closing this issue in favour of #14 . Let's discuss new icons there :)
