### ISSUE TITLE
Simulate PKPushPayload

### ISSUE THREAD

**Issue by sshah8x8** [noodlewerk/NWPusher#27]
Hello,
Great app and library. Currently push notification get sent to the 
```
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
```
I want to capture them in 
```
- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(NSString *)type
```

with PKPushRegistry type ```PKPushTypeVoIP```

Any tips?

Thanks.

**Comment by Shebuka** [comment]
You need to select the appropriate PushKit VoIP certificate in Pusher and APNs would automatically deliver to your device a `PKPushTypeVoIP`

**Comment by leonardvandriel** [comment]
Thanks @Shebuka. @sshah8x8, does that resolve the issue?
