### ISSUE TITLE
Device token size is variable length.

### ISSUE THREAD

**Issue by mikevbaker** [noodlewerk/NWPusher#28]
I've been trying to add push notification to my app this morning and I'm running into an issue with the device token. In the Readme it says that the device token size is 64 characters and there is code to handle this. However in [this](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html) documentation it says 

> "Important: APNs device tokens are of variable length. Do not hardcode their size."

When I run this code: 

	func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]? = nil) -> Bool
	{
		...

		// PUSH notification
		let center = UNUserNotificationCenter.current()
		center.requestAuthorization(options: [.alert, .sound, .badge]) {
			granted, error in
			if granted == true {
				Logger.add("Notifications granted")
			}
			if let error = error {
				Logger.add("Error getting notifications grant \(error)")
			}
		}
		UIApplication.shared.registerForRemoteNotifications()
		
		return true
	}

	func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {

		let str1 : String = String(describing: deviceToken)
		let str2 = String(data: deviceToken, encoding: String.Encoding.utf32)
		let str3 : String = deviceToken.base64EncodedString()
		print("original token \(deviceToken)")
		print("str1 \(str1)")
		print("str2 \(str2)")
		print("str3 \(str3)")
	}

The results are this:
2016-08-23 12:14:15.550336 Ree SE[1137:587543] Notifications granted
original token 32 bytes
str1 32 bytes
str2 nil
str3 FkIgF1jqz8X0mMX4IG1YnpyjeTBwgoGsODqHs0Cag/s=

The last one's the only one that looks like it might be a token but it's not 64 characters. I tried various encoding types other than utf32 but nothing came up looking right at all. Is there something I'm doing wrong in getting the token? What about the discrepancy in the documentation?

Mike

**Comment by leonardvandriel** [comment]
Hi Mike, The device token is provided by the OS as binary data of 32 bytes (256 bit). Represented in hexadecimal that is 64 characters (0-9A-F). `NWNotification` provides a helper method `hexFromData` for turning binary `Data` to hex `String`. Try:

    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        let hex = NWNotification.hexFromData(deviceToken)
        print("\(hex)")
    }

**Comment by mikevbaker** [comment]
Hi,

 

Thanks for the info. Following your example I crafted one for Swift 3 in my string extension. Currently I don’t have NWPusher in the iOS app that I’m building. Now just need to implement didReceiveRemoteNotification to see if I’m getting something J

 

Thanks,

Mike

**Comment by grosch** [comment]
@mikevbaker Do it like so:

`let token = deviceToken.reduce("") { $0 + String(format: "%02x", $1) }`
