### ISSUE TITLE
Changing values in `~/Library/Pusher/config.plist` are overwritten when restarting pusher 

### ISSUE THREAD

**Issue by Andruschenko** [noodlewerk/NWPusher#29]
At startup the Log tells me `Loaded config from /Users/myUserName/Library/Pusher/config.plist`. 
So I wanted to change the defaults in that .plist file. But the changes never show effect and the restart of `Pusher` leads to the content being the default again.

Would be great to being able to customize the default payload.

**Comment by leonardvandriel** [comment]
Hi, The `config.plist` is overwritten when closing the application. Therefore make sure you first close the Pusher app before manually editing the file. Does that resolve the issue?

**Comment by leonardvandriel** [comment]
Hi @Andruschenko, did you get a change to try out the above suggestion?
