### ISSUE TITLE
Cannot connecting to APNS

### ISSUE THREAD

**Issue by bill350** [noodlewerk/NWPusher#30]
Hi,

I don't know if it is related to the Keynote of today but it seems that we have connecting issues :

![Connecting](https://cloud.githubusercontent.com/assets/2437702/18312230/eddec224-7508-11e6-994a-163c549abe01.png)
![Failure](https://cloud.githubusercontent.com/assets/2437702/18312231/edefa008-7508-11e6-9e9e-8d269b984fab.png)

Version 0.7.0 (15)

Thanks

**Comment by leonardvandriel** [comment]
Hi, Could you please update to the latest version (0.7.3) and confirm this issue remains unresolved? Also consider that poor internet connectivity might have caused this issue. Thanks

**Comment by bill350** [comment]
Hi, it seems than we have some problem with our new firewall (it works on another network), can you shared some details about APNS connections / ports ? I think it will be usefull for other users too ;)
Thanks

**Comment by leonardvandriel** [comment]
Thanks. I added an entry in the Troubleshooting section, see commit https://github.com/noodlewerk/NWPusher/commit/5bab81d099debd6fc7fddccbf4324dfa1c387e40

**Comment by bill350** [comment]
Thanks for the details ;)
