### ISSUE TITLE
Allow apostrophe

### ISSUE THREAD

**Issue by grosch** [noodlewerk/NWPusher#31]
Why do you force double quotes for strings?

**Comment by leonardvandriel** [comment]
Hi, 

May I assume that you are referring to the quotes in the payload? If so, that string is JSON formatted, which is the required format by Apple's Push Notification Service.

Please elaborate if I've interpreted your report incorrectly.

**Comment by grosch** [comment]
Nope, you're correct.  I was just being a dork apparently.
