### ISSUE TITLE
Rich Content Push Notifications not going through

### ISSUE THREAD

**Issue by tettoffensive** [noodlewerk/NWPusher#36]
Push notifications with `"mutable-content":0` are delivered right away, but I'm trying to test to see if rich push notifications are working with my app via the Pusher desktop app with this payload and they don't seem to be delivered to my iPhone.

Is there some reason why Pusher would not support this? Or maybe it's Apple that's failing to deliver, but as far as I can tell the payload is correct.

```json
{
  "aps": {
    "alert": {
      "title": "Realtime Custom Push Notifications",
      "subtitle": "Now with iOS 10 support!",
      "body": "Add multimedia content to your notifications"
    },
    "sound": "default",
    "badge": 1,
    "mutable-content": 1,
    "category": "realtime",
    "data": {
      "attachment-url": "https://framework.realtime.co/blog/img/ios10-video.mp4"
    }
  }
}
```

**Comment by leonardvandriel** [comment]
Hi @tettoffensive,

Pushes with `mutable-content` seem to work fine. I'm actually using this in production myself. There is indeed no reason why Pusher would not support it. In fact, Pusher is agnostic to the content of the push payload. Did the issue persist?

**Comment by tettoffensive** [comment]
@leonardvandriel thanks for the reply. Eventually, I got it to work. It was just very difficult to debug the extension. There were some gotchas. But it wasn't related to pusher

**Comment by commando24** [comment]
@tettoffensive can you tell us the steps you have performed to make it work ?

**Comment by tettoffensive** [comment]
@commando24 Unfortunately, not. This was over 2.5 years ago. I wish I had put more details.
