### ISSUE TITLE
APNS Auth key .p8 support

### ISSUE THREAD

**Issue by crsantos** [noodlewerk/NWPusher#37]
This is more a suggestion/question. You can tag it appropriately.

Does this support the new `.p8` file as certificate - APNs Auth Key?

**Comment by leonardvandriel** [comment]
The .p8 format does not seem to apply to the binary interface that NWPusher uses. Therefore I don't expect support to be added. You can still generate the old fashioned .p12 files, see: http://stackoverflow.com/questions/39672297/how-to-use-apples-new-p8-certificate-for-apns-in-firebase-console.

**Comment by crsantos** [comment]
@leonardvandriel Thanks for the advice 💪
