### ISSUE TITLE
Unable to connect (-9810)

### ISSUE THREAD

**Issue by jedofus** [noodlewerk/NWPusher#39]
Hello, i have this error : 
**Unable to connect: SSL handshake failed (-9810)** 
i check sandbox environment and unchecked but I still have this problem.
How can i resolved it ?

**Comment by JanC** [comment]
Hi,
this is a SSL connection problem. Are you sure you are using the correct client certificate? Are you using any https proxy?

**Comment by leonardvandriel** [comment]
Hi @jedofus,

According to the docs, -9810 is an 'Internal Error' (`errSSLInternal`), which unfortunately is not very descriptive. A cause discussed online is related to use of proxies, as @JanC already suggested. See: https://lists.apple.com/archives/macnetworkprog/2005/Mar/msg00001.html. @jedofus, are you using a proxy?

I added this specific error to app, so I will be reported as `SSL handshake internal error` (commit 65738ca).
