### ISSUE TITLE
Notifications to ALL devices

### ISSUE THREAD

**Issue by LuisRodriguezLD** [noodlewerk/NWPusher#42]
Is there a way to send the notification to ALL devices?
So far I only managed to send to one device using the Token
but if I try without the token I can't send it.

**Comment by JanC** [comment]
How should that work? You **need** a push token to send a push message

**Comment by LuisRodriguezLD** [comment]
But what if I want to send a PushNotification to ALL devices?
What would be the best way to do that?

(Please excuse my lack of knowledge on the subject. I am new at this.)

**Comment by JanC** [comment]
If you want to send a push to all your users, you first need to collect all the push tokens and send the pushes one by one. Again, I recommend to read the Apple docs first.

**Comment by LuisRodriguezLD** [comment]
Thank you so much!
