### ISSUE TITLE
Installing NWPusher on OS X 10.9.5

### ISSUE THREAD

**Issue by juandres89** [noodlewerk/NWPusher#43]
Hi, I have installed NWPusher both with "brew" and "binary" as you say but it was not possible to run it after installing. Is it necessary to have some OSX version?

**Comment by leonardvandriel** [comment]
Hi @juandres89, Please describe what happens in more detail. Does it give an error message?

**Comment by juandres89** [comment]
Thank you, the message is as follows:
____________________________________
Process:         Pusher [5153]
Path:            /Applications/Pusher.app/Contents/MacOS/Pusher
Identifier:      com.noodlewerk.Pusher
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [352]
Responsible:     Pusher [5153]
User ID:         501

Date/Time:       2017-01-19 17:34:29.595 -0500
OS Version:      Mac OS X 10.9.5 (13F1808)
Report Version:  11
Anonymous UUID:  98E2312B-28AB-DACB-554F-16003188CC7F

Sleep/Wake UUID: B06A65FB-BC21-4564-A62D-A9DF07F1D66F

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: ___NSArray0__
  Referenced from: /Applications/Pusher.app/Contents/MacOS/../Frameworks/PusherKit.framework/Versions/A/PusherKit
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /Applications/Pusher.app/Contents/MacOS/../Frameworks/PusherKit.framework/Versions/A/PusherKit

**Comment by leonardvandriel** [comment]
This might be related to OS X Mavericks, which might not support the type of NSArray. Unfortunately I don't have OS X Mavericks to reproduce this issue. If you have Xcode installed, you can try building from source. Is that an option for you?

**Comment by juandres89** [comment]
I will try with Xcode and then let you know ! Thank you so much for answering soon.
