### ISSUE TITLE
Retrieving device token for Mac 

### ISSUE THREAD

**Issue by dylib** [noodlewerk/NWPusher#44]
I'm curious how to go about getting the device token for a Mac that I would like to push to? 

I noticed the documentation [shows an example for iOS](https://github.com/noodlewerk/NWPusher#device-token), although maybe [NWPusher](https://github.com/noodlewerk/NWPusher) is made more specifically for iOS and I'm out of bounds thinking it's for macOS too.

**Comment by leonardvandriel** [comment]
hi @dylib, excellent question. I haven't tried pushing to OS X. Would you be willing to look into this and share your insight?

**Comment by dylib** [comment]
@leonardvandriel: I think that I've found the information, however, I haven't tried it yet. If you want to add the information below to your readme it might be helpful (original information located on "[Configuring Remote Notification Support](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW3)" page on the Apple Developer Site).

**Obtaining a Device Token on macOS**

On macOS, you obtain a device token for your app by calling the ```registerForRemoteNotificationTypes:``` method of the NSApplication object. It is recommended that you call this method at launch time as part of your normal startup sequence. The first time your app calls this method, the app object requests the token from APNs. After the initial call, the app object contacts APNs only when the device token changes; otherwise, it returns the existing token quickly.

The app object notifies its delegate asynchronously upon the successful or unsuccessful retrieval of the device token. You use these delegate callbacks to process the device token or to handle any errors that arose. You must implement the following delegate methods to track whether registration was successful:

- Use the application:didRegisterForRemoteNotificationsWithDeviceToken: to receive the device token and forward it to your server.
- Use the application:didFailToRegisterForRemoteNotificationsWithError: to respond to errors.

**Note**
> If the device token changes while your app is running, the app object calls the appropriate delegate method again to notify you of the change.

**How to fetch the device token for your macOS app.** 

The app delegate calls the ```registerForRemoteNotificationTypes:``` method as part of its regular launch-time setup, passing along the types of interactions that you intend to use. Upon receiving the device token, the ```application:didRegisterForRemoteNotificationsWithDeviceToken:``` method forwards it to the app’s associated server using a custom method. If an error occurs during registration, the app temporarily disables any features related to remote notifications. Those features are re-enabled when a valid device token is received.

**Registering for remote notifications on macOS**

**Objective-C**

    - (void)applicationDidFinishLaunching:(NSNotification *)notification {
        // Configure the user interactions first.
        [self configureUserInteractions];
     
        [NSApp registerForRemoteNotificationTypes:(NSRemoteNotificationTypeAlert | NSRemoteNotificationTypeSound)];
    }
     
    - (void)application:(NSApplication *)application
            didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
        // Forward the token to your server.
        [self forwardTokenToServer:deviceToken];
    }
     
    - (void)application:(NSApplication *)application
            didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
        NSLog(@"Remote notification support is unavailable due to error: %@", error);
        [self disableRemoteNotificationFeatures];
    }

**Swift**

    func applicationDidFinishLaunching(_ aNotification: Notification) {
        // Configure the user interactions first.
        self.configureUserInteractions()
        
        NSApplication.shared().registerForRemoteNotifications(matching: [.alert, .sound])
    }
     
    // Handle remote notification registration.
    func application(_ application: NSApplication,
                     didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        // Forward the token to your server.
        self.forwardTokenToServer(token: deviceToken)
    }
     
    func application(_ application: NSApplication,
                     didFailToRegisterForRemoteNotificationsWithError error: Error) {
        // The token is not currently available.
        print("Remote notification support is unavailable due to error: \(error.localizedDescription)")
    }
```

**Comment by dylib** [comment]
**Update**: I tried the code above in a ```macOS``` application and it worked great with ```NWPusher```.

**Comment by leonardvandriel** [comment]
thanks @dylib. I'll add it to the readme.
