### ISSUE TITLE
hi~thank you for this tool ,but I have a question

### ISSUE THREAD

**Issue by yang7** [noodlewerk/NWPusher#46]
I saw a function like this
`- (NWEnvironment)preferredEnvironmentForCertificate:(NWCertificateRef)certificate
{
    NWEnvironmentOptions environmentOptions = [NWSecTools environmentOptionsForCertificate:certificate];
    
    return (environmentOptions & NWEnvironmentOptionSandbox) ? NWEnvironmentSandbox : NWEnvironmentProduction;
}`

I don't understand the return value.
 there is only one situation the function will return NWEnvironmentProduction,when environmentOptions is NWEnvironmentOptionNone
I want to know what situation NWEnvironmentProduction or NWEnvironmentAuto will be used

**Comment by leonardvandriel** [comment]
@yang7, I think you're mistaking the `&` operator for `|`.

`environmentOptions & NWEnvironmentOptionSandbox` evaluates to true if `environmentOptions` is `NWEnvironmentOptionSandbox` or `NWEnvironmentOptionAny`, which is the case for certificates for the type `kNWCertTypeIOSDevelopment`, `kNWCertTypeMacDevelopment`, `kNWCertTypeSimplified`, `kNWCertTypeWebProduction`, `kNWCertTypeVoIPServices`, and `kNWCertTypeWatchKitServices`.
