### ISSUE TITLE
Can't send custom Payload other than APS 

### ISSUE THREAD

**Issue by guhan0** [noodlewerk/NWPusher#52]
Please add a provisioning to send a custom payload along with APS key.

**Comment by JanC** [comment]
I'm using pusher and the method `-[NWPusher pushPayload:token:identifier:error:]` allows you to send any kind of JSON. 

You just have to serialize your JSON object into a JSON string.

**Comment by guhan0** [comment]
{
	"aps":
 	{
		"alert":"Testing.. (70)",
		"badge":10,
		"category":"MAIL",
		"content-available":1,
		"mutable-content":1,
		"sound":"default"
	};
	"addInfo":
	{
		"testKey":"TestValue"
	}
}
This type of Payload is not working

**Comment by JanC** [comment]
Your JSON is malformed. This should work

```
{
  "aps": {
    "alert": "Testing.. (70)",
    "badge": 10,
    "category": "MAIL",
    "content-available": 1,
    "mutable-content": 1,
    "sound": "default"
  },
  "addInfo": {
    "testKey": "TestValue"
  }
}
```
