### ISSUE TITLE
Failed to connect to APNS

### ISSUE THREAD

**Issue by arorajatin** [noodlewerk/NWPusher#53]
Pusher was working just fine until a few days back. Now, it does not seem to be connecting to APNS and fails with the error log mentioned below.

`Connecting to APN... (app_bundle_id sandbox)`
`Unable to connect: Socket connecting failed (-1)`

I'm on MacOS Sierra 10.12.4 and I have tried connecting using both the sandbox and the production certificates, but it fails with the same error in both the cases. 

Any ideas as to what might be happening?

**Comment by leonardvandriel** [comment]
Perhaps there was a temporary outage. I just confirmed that the latest version (0.7.5) is working. Are you perhaps behind a firewall or using a proxy? Also, see if your push certificate is still valid and your developer account is active.

**Comment by arorajatin** [comment]
It was a firewall issue indeed. Tried with my mobile network, it worked. Thanks for your help. 👍
