### ISSUE TITLE
Add support for APNS auth token (p8)

### ISSUE THREAD

**Issue by BenchR267** [noodlewerk/NWPusher#55]
Apple provides a way to send push notifications without the need of certificates by creating never expiring authentication keys (http://stackoverflow.com/questions/39943701/how-to-send-apns-push-messages-using-apns-auth-key-and-standard-cli-tools).
Unfortunately NWPusher does not support this kind of authentication yet.

**Comment by JanC** [comment]
See https://github.com/noodlewerk/NWPusher/issues/54

**Comment by BenchR267** [comment]
Isn't that a different thing? #54 is about using certificates over http/2 🤔

**Comment by JanC** [comment]
Well .. since the Pusher supports only the binary apple API and there are no plans to use the HTTP API, it means that it does not use the http (or http/2) API which is needed for sending pushes with [token authentication.](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html)

**Comment by BenchR267** [comment]
Makes sense. So it's related, but not the same.

**Comment by JanC** [comment]
btw, I'm using Knuff but it also does not support token based auth :/
https://github.com/KnuffApp/Knuff/issues/62

**Comment by andrejbroncek** [comment]
Do you guys know of any alternative that might have support for this?

**Comment by onmyway133** [comment]
@andrejbroncek @BenchR267 in the meantime, you can use https://github.com/onmyway133/PushNotifications which supports APNS certificate, token and FCM authentication, works on both iOS and Android

**Comment by jaymehtasa** [comment]
Pusheverapp free version does the job...
https://pushever.app/

Downloadable Mac App - https://github.com/cupnoodle/pusheverapp/releases/download/2.0t/PusheverTrial.app.zip
