### ISSUE TITLE
Unable to connect: SSL handshake connection closed via error

### ISSUE THREAD

**Issue by AnthonyUccello** [noodlewerk/NWPusher#59]
Hi

I saw other threads that had this error with an error code but I am getting this error with no error code.

I have a valid push certificate and whenever I try to select it from the keychain or import the .p12 I get this error.

Any ideas? 

Update:

When I check the status object in NWSSLConnection I get -9806

Update 2: Oddly if I uncheck the `Should Use Sandbox` it connects to the production. However the second I try to push in that environment I get the error:

`Unable to read: Read connection closed`

Update 3: It looks like messed up security settings on the company Wifi. When I pair with my phone and use that data, I connect just fine.

**Comment by leonardvandriel** [comment]
Hi @AnthonyUccello, thanks for solving the issue.
