### ISSUE TITLE
Any Plans to support Apple Authentication Key (.p8) files?

### ISSUE THREAD

**Issue by Blackjacx** [noodlewerk/NWPusher#60]
Hi there,

since a while Apple supports authentication keys that never expire and can be re-configured after creation. Some services already support this. Any plans my favourite push testing utility supports this too in near future?

**Comment by leonardvandriel** [comment]
Hi @Blackjacx, thanks for the considerate argumentation. At this point there are no plans to support this. There's little overlap with the deprecated binary interface, so it would either require a significant redesign or starting from scratch. I figure a new tool, from the ground up, would be a better approach, but not something I've had time for. There's more discussion here: https://github.com/noodlewerk/NWPusher/issues/55.
